Converting OverlapEncodings Rnw file to Rmd
Bioconductor/GenomicAlignments pull request #24
Opened 2023-01-09 20:33 UTC by BerylKanali

Hi @jwokaty
 [HTML](https://rpubs.com/BerylK/990508) and [PDF](https://bioconductor.org/packages/devel/bioc/vignettes/GenomicAlignments/inst/doc/OverlapEncodings.pdf) for comparison.
`RMD Build` and `RMD Check` passed.

Tried to do some self review. Hopefully it will have less issues.to be changed.

2023-01-13 18:03 UTC, jwokaty requested changes
Good work this vignette. It was quite long. There are a few issues to address within the document. Note that it's important to compare the HTML and the PDF to catch problems.

According to Marcel, the footnotes going to the bottom is related to a Pandoc issue, so we'll leave them as they are.

Please remove extra lines and format paragraphs with `Code > Reflow comment`.

2023-01-13 18:03 UTC, jwokaty commented on DESCRIPTION
> +	  comment="Converted 'OverlapEncodings' vignette from Sweave to RMarkdown."))
Please use the same indentation as line 18.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +date: "Edited: December 2016; Compiled: `r format(Sys.time(), '%B %d , %Y')`"
Use `Last modified`  rather than `Edited`

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +
Please remove all extra lines.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +BAM file *untreated3_chr4.bam* (located in the `r Biocpkg("pasillaBamSubset")` data package) contains paired-end reads from the
Please reformat long lines like this one with `Code > Reflow comment`.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +# Detect ``almost splice compatible'' overlaps
Change to double quotes around `almost splice compatible`.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +Biocpkg("GenomicFeatures")` package to make a `TxDb` object containing the dm3
This doesn't render the link for GenomicFeatures correctly--is it because of the line break?

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +`TxDb` packages). One of them is the `TxDb.Dmelanogaster.-UCSC.-dm3.ensGene`
`TxDb.Dmelanogaster.UCSC.dm3.ensGene` is a package, so we should generate the link. Remove the `-` in name.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +``flipped'' read) is aligned with the first base of the exon. For `"1:j:"`, the
Remove the extra back ticks and double apostrophes. Only "1:j:" should be in back ticks.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +encoding is "splice compatible" if its 2 halves are ``splice compatible''.
Replace backticks and single quotes with a set of double quotes around "splice compatible".

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +- `"2{-}{-}2:jm{-}{-}mm:af{-}{-}jm:aa{-}{-}af:"`
Compare to existing PDF. It looks like the hyphens have extra braces around them that should be removed.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +`BSgenome.Dmelanogaster.UCSC.dm3` data package ^[See
Generate the link for `BSgenome.Dmelanogaster.UCSC.dm3`

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +```
Remove. One of the requirements of a vignette is that it must not install anything especially without the user's the knowledge.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +nucleotide sequences for each ``splice compatible'' overlap. If we use the
Fix the double quotes around `splice compatible`

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +Finally, since BAM file {\tt untreated1\_chr4.bam} is not the full output of the
Remove the braces and `\tt` surrounding `untreated1_chr4.bam` as it's preventing it from showing up.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +- `"2{-}{-}2:jm{-}{-}mm:am{-}{-}mm:af{-}{-}jm:aa{-}{-}af:"`
Compare with original PDF. This section seems to have problems like the earlier section where braces surround hyphens.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +^[http://samtools.sourceforge.net/] for the details), as well as reads not
Since it's just a URL, let's make `SAM Spec` a link with the footnote URL so we can remove/reduce the footnotes.

2023-01-13 18:03 UTC, jwokaty commented on vignettes/OverlapEncodings.Rmd
> +Browser^[http://genome.ucsc.edu/cgi-bin/hgGateway]. The Bioconductor project
Since this is another URL, let's make UCSC Genome Browser a link rather than use a footnote.

2023-01-18 04:18 UTC, hpages commented
@BerylKanali @jwokaty Please make sure that things like this (from section 5.1.1):

![overlap_encodings_5_1_1](https://user-images.githubusercontent.com/8810451/213082336-3510a4e9-113b-420c-b10f-96e20b55b190.png)

or this (from section 5.2.1):

![overlap_encodings_5_2_1](https://user-images.githubusercontent.com/8810451/213082210-cc26f1a6-d062-45ab-973e-859ed072b3c4.png)

are rendered properly. I don't know how to do this, hopefully it's possible! :crossed_fingers: 

This is a tough vignette, but, AFAIK, not a very visited/popular one. I wonder if it's worth the effort of converting to Rmd :disappointed: 

Thanks,
H.

2023-01-18 08:23 UTC, BerylKanali commented
> @BerylKanali @jwokaty Please make sure that things like this (from section 5.1.1):
> 
> ![overlap_encodings_5_1_1](https://user-images.githubusercontent.com/8810451/213082336-3510a4e9-113b-420c-b10f-96e20b55b190.png)
> 
> or this (from section 5.2.1):
> 
> ![overlap_encodings_5_2_1](https://user-images.githubusercontent.com/8810451/213082210-cc26f1a6-d062-45ab-973e-859ed072b3c4.png)
> 
> are rendered properly. I don't know how to do this, hopefully it's possible! 🤞
> 
> This is a tough vignette, but, AFAIK, not a very visited/popular one. I wonder if it's worth the effort of converting to Rmd 😞
> 
> Thanks, H.

@hpages We had noticed some elements in the PDF did not render properly when we compared it to the code, This is how section 5.2.1 appears now in the HTML file. The paired-end encodings appear in full, in the PDF they were somehow slashed. Let me know if this is okay.
<img width="479" alt="Capture" src="https://user-images.githubusercontent.com/50364045/213119976-95816c1f-a13a-4848-905b-a98f74ac403c.PNG">

2023-01-18 15:00 UTC, LiNk-NY commented
@BerylKanali 
Hi Beryl, 
The figures don't look quite like the ones above. 
Perhaps you can use `\preformatted{}` tags?

2023-01-20 13:44 UTC, BerylKanali commented
> @BerylKanali Hi Beryl, The figures don't look quite like the ones above. Perhaps you can use `\preformatted{}` tags?

Hi @LiNk-NY Do you mean these figures?
<img width="246" alt="Capture4" src="https://user-images.githubusercontent.com/50364045/213710203-aa76562f-1c41-4738-91a0-12acbb3cbdc4.PNG">

2023-01-20 13:53 UTC, LiNk-NY commented
@BerylKanali Hi Beryl

> Hi @LiNk-NY Do you mean these figures?
> <img width="246" alt="Capture4" src="https://user-images.githubusercontent.com/50364045/213710203-aa76562f-1c41-4738-91a0-12acbb3cbdc4.PNG">
> 

The alignment should be maintained

2023-06-28 14:48 UTC, jwokaty commented
`\preformatted{}` doesn't seem to work, but could work `<pre></pre>`

2024-03-25 16:59 UTC, hpages commented
@jwokaty Is it ok to close this?

2025-04-21 18:47 UTC, hpages commented
I take your "thumb up" as a yes @jwokaty

2025-04-21 18:47 UTC, closed without merging