Converted .Rnw to .Rmd and edited DESCRIPTION file
Bioconductor/GenomicAlignments pull request #28
Opened 2023-04-30 10:49 UTC by Rohit-Satyam

2023-08-08 18:51 UTC, jwokaty commented on DESCRIPTION
> +        email = "maintainer@bioconductor.org", role = "cre"))
Herve is the maintainer, so remove lines 24-25. 

Line 23 should be  formatted like `email` on line 18. It should have the same indent and no spaces around the `=`.

Replace the ending comma with a closing parenthesis.

2023-08-08 18:56 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +knitr::opts_chunk$set(collapse = TRUE,eval = T)
`eval`'s default is TRUE, so you don't have to set it. Also I advise against using `T` for `TRUE`.

2023-08-08 19:05 UTC, hpages commented
@Rohit-Satyam @jwokaty This PR contains long diffs where most of the lines included in the diffs show no differences. This seems to be a the result of CRLF pollution. Maybe your editor @Rohit-Satyam automatically introduces CRLF line terminators in the files you touch? Please remove the CRLF's and make sure that `git diff GenomicAlignments-rmd devel` displays only the lines that have effectively been modified. Thanks!

2023-08-08 19:29 UTC, jwokaty commented on vignettes/references.bib
@hpages @Rohit-Satyam I would like to confirm that the the right references have been selected. In the current vignette, the references are listed as 

* http://www-huber.embl.de/users/anders/HTSeq/doc/overview.html 
* http://www-huber.embl.de/users/anders/HTSeq/doc/count.html

However, these references no longer exist. Rohit tried to replace the references with those in this document. @hpages Could you confirm they are correct? If these are correct, I believe the htseq readthedocs has a specific format for citing that we should follow, but first let's make sure we have the right references.

2023-08-08 19:38 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +Anders [@Anders2019][@Putri2022].
This produces `[Putri et al. (2019)](Putri et al. 2022)`. If you put a space in between the two references, they will render as `(Putri et al. 2019) (Putri et al. 2022)`. Please insert a space.

2023-08-08 19:42 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +date: "`r format(Sys.Date(), '%d %B, %Y')`"
This vignette has both an "edited date" and a "compiled date". Please modify the date as

    date: "Edited: April 2016; Compiled: `r format(Sys.Date(), '%d %B, %Y')`"

2023-08-08 19:45 UTC, jwokaty commented on vignettes/summarizeOverlaps-modes.svg
@hpages This image has a bad link in it. It could be removed or corrected if the correct link is known.

2023-08-08 19:47 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +`features` argument. When annotation regions of interest are defined by
Start a new paragraph at `When annotation regions of interest are defined by`.

2023-08-08 19:48 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +the result would be counts per exon. When the region of interest is
Start a new paragraph at `When the region of interest is`

2023-08-08 19:50 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +genes, the result would be counts per gene. The combination of defining
Start a new paragraph at `The combination of defining`

2023-08-08 19:51 UTC, jwokaty commented on vignettes/summarizeOverlaps.Rmd
> +biological problems. This next example demonstrates how the same read
Start a new paragraph at `This next example demonstrates how`

2023-08-08 19:52 UTC, hpages commented on vignettes/references.bib
I'm not that familiar with `summarizeOverlaps()` or HTSeq. However IIRC the former was trying to mimic version 1.0 of the latter so maybe a reference to the original paper from 2014 would be more appropriate. See https://htseq.readthedocs.io/en/latest/#citation for the full citation of the original paper.

2023-08-08 19:58 UTC, hpages commented on vignettes/summarizeOverlaps-modes.svg
You could use this link `https://htseq.readthedocs.io/en/release_0.11.1/count.html`

2023-08-08 20:03 UTC, jwokaty requested changes
@Rohit-Satyam Thanks for this PR. Both Herve and I have made some comments to improve the PR.

2024-03-25 16:59 UTC, hpages commented
@Rohit-Satyam @jwokaty Where do we stand on this and what's the next step? Thanks

2025-04-21 18:44 UTC, closed without merging